// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wedding.Models
{
    public partial class Assistance
    {
        public Guid Uuid { get; set; }

        public virtual Extra Uu { get; set; }
        public virtual Guest UuNavigation { get; set; }
    }
}