// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wedding.Models
{
    public partial class Extra
    {
        public Guid Uuid { get; set; }
        public string User { get; set; }

        public virtual Assistance Assistance { get; set; }
        public virtual Attendance Attendance { get; set; }
        public virtual Desert Desert { get; set; }
        public virtual Food Food { get; set; }
    }
}