// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wedding.Models
{
    public partial class Redeem
    {
        public Redeem()
        {
            Guests = new HashSet<Guest>();
        }

        public int Id { get; set; }
        public Guid Code { get; set; }

        public virtual Kid Kid { get; set; }
        public virtual Peer Peer { get; set; }
        public virtual ICollection<Guest> Guests { get; set; }
    }
}